
# Tutorial de Numpy
# http://bit.ly/2ECWwjg


"Numpy" es la abreviatura de "Numerical Python".

Numpy nos proporciona operaciones sobre arrays multi-dimensionales muy eficientes.

Numpy nos permite operar con Vectores o Matrices.

La características clave de Numpy son:
- ndarrays: array de n dimensiones con el mismo tipo de datos, optimizado para un cálculo rápido y eficiente.
- Broadcasting: herramienta que facilita la operación con arrays de diferentes dimensiones.
- Vectorización: permite operaciones aritméticas con ndarrays
- Input/Output: simplifica la lectura y escritura de datos en ficheros.

Otros Recursos sobre Numpy:
- Manual de Referencia: https://docs.scipy.org/doc/numpy-1.13.0/reference/
- Python for Data Analysis, Wes McKinney
- Python Data Science Handbook, Jave VanderPlas


# Introducción

**ndarrays** son arrays multi-dimensionales optimizados para un cálculo rápido y eficiente.


## Creación de un Vector o Array de 1 dimensión

In [1]:
import numpy as np
np.__version__

'1.13.3'

In [2]:
# Creamos un array de 1 dimensión
an_array = np.array([3, 33, 333])

print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
# Consultamos las dimensiones del array
print(an_array.shape)

(3,)


In [4]:
# Accedemos al array con 1 indice, ya que tiene 1 dimensión
print(an_array[0], an_array[1], an_array[2]) 

3 33 333


In [5]:
# ndarrays son mutables, podemos modificar los elementos del array
an_array[0] = 888

print(an_array)

[888  33 333]


## Creación de una Matriz o Array de 2 dimensiones

Un Array de 2 dimensiones es una Matriz y proporciona todas las operaciones habituales para el cálculo matricial.

In [6]:
# Crear una Matriz
another = np.array([[11,12,13],[21,22,23]])

print(another)

print("Las dimensión de la mátriz creada es (filas, columnas):", another.shape)

print("Accediendo a los elementos [0,0], [0,1] y [1,0]: ", another[0,0], ", ", another[0,1], ", ", another[1,0])

[[11 12 13]
 [21 22 23]]
Las dimensión de la mátriz creada es (filas, columnas): (2, 3)
Accediendo a los elementos [0,0], [0,1] y [1,0]:  11 ,  12 ,  21



## Creación de Arrays

Podemos crear Arrays con diferentes funciones de Numpy.

In [7]:
import numpy as np

# Crear un array 2x2 con ceros
ex1 = np.zeros((2,2))      
print(ex1)                              

[[ 0.  0.]
 [ 0.  0.]]


In [8]:
# Crear un array 2x2 con 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

[[ 9.  9.]
 [ 9.  9.]]


In [9]:
# Crear una matriz identidad (con todos los elementos de la diagonal igual a 1)
ex3 = np.eye(2,2)
print(ex3)  

[[ 1.  0.]
 [ 0.  1.]]


In [10]:
# Crear un arrar con 1
ex4 = np.ones((1,2))
print(ex4)    

[[ 1.  1.]]


In [ ]:
# El array ex4, que hemos creado, es un array de dimension 1x2
print(ex4.shape)

# Tenemos que acceder usando 2 indices
print()
print(ex4[0,1])

In [11]:
# Crear un array con números aleatorios entre 0 y 1
ex5 = np.random.random((2,2))
print(ex5)    

[[ 0.97645211  0.78284647]
 [ 0.14528419  0.42901837]]


## Indexación de Arrays

La indexación nos permite obtener sub-arrays de un array.

In [12]:
import numpy as np

# Crear una matriz de dimensiones 3 x 4
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [15]:
# Obtener un subarray de 2 x 2
a_slice = an_array[:2, 1:3]
print(a_slice)

[[1000   13]
 [  22   23]]


In [16]:
# Modificar un subarray también modifica el array original
print("Before:", an_array[0, 1]) 
a_slice[0, 0] = 1000
print("After:", an_array[0, 1])

Before: 1000
After: 1000


In [17]:
# Crear un nuevo array copiando de un array
an_array[0:1] = 12
a_slice = np.array(an_array[:2, 1:3])
print(a_slice)

[[12 12]
 [22 23]]


In [18]:
# Modificar una copia no modifica el array original
print("Before:", an_array[0, 1]) 
a_slice[0, 0] = 1000
print("After:", an_array[0, 1])

Before: 12
After: 12


La indexación nos permite obtener filas o columnas de un array.

In [19]:
# Crear una matriz de dimensiones 3 x 4
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [20]:
# Obtener una Fila de un Array como Vector de dimensión 4
row_rank1 = an_array[1, :]

print(row_rank1, row_rank1.shape)
print(row_rank1[2])

[21 22 23 24] (4,)
23


In [21]:
# Obtener una Fila de un Array como Matriz de dimensión 1 x 4
row_rank2 = an_array[1:2, :]

print(row_rank2, row_rank2.shape)
print(row_rank2[0,2])

[[21 22 23 24]] (1, 4)
23


In [22]:
# Obtener una Columna de un Array
print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


## Indexación Avanzada con Array de Indices

Nos permite acceder/modificar elementos de un array de indices

In [23]:
# Crear un nuevo array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Array:')
print(an_array)

Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [24]:
# Crear un array de indices
col_indices = np.array([0, 1, 2, 0])
print('\nIndices de Columna: ', col_indices)

row_indices = np.arange(4)
print('\nIndices de Fila : ', row_indices)


Indices de Columna:  [0 1 2 0]

Indices de Fila :  [0 1 2 3]


In [25]:
# Obtener un array de filas y columnas
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [26]:
# Consultar los valores del array
print('Consultar valores del array: ',an_array[row_indices, col_indices])

Consultar valores del array:  [11 22 33 41]


In [27]:
# Modificar los valores del array
an_array[row_indices, col_indices] += 100000

print('\nArray:')
print(an_array)


Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


## Indexación Avanzada con Array de Booleanos

Nos permite acceder/modificar elementos de un array de Booleanos

In [28]:
# Crear un array de 3x2
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [29]:
# Crear un filtro o array de Booleanos
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [30]:
# Consultar valores de un array
print(an_array[filter])

[21 22 31 32]


In [31]:
# Crear un filtro
filter = ((an_array > 20) & (an_array < 30))
filter

array([[False, False],
       [ True,  True],
       [False, False]], dtype=bool)

In [32]:
# Consultar valores de un array
print(an_array[(an_array > 20) & (an_array < 30)])

[21 22]


In [33]:
# Consultar valores de un array
an_array[(an_array % 2 == 0)]

array([12, 22, 32])

In [34]:
# Modificar valores de un array
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


# Tipos de Datos y Operaciones con Arrays

## Tipos de Datos

Un **ndarray** tiene un tipo de datos único

In [35]:
ex1 = np.array([11, 12])
print(ex1.dtype)

int32


In [36]:
ex2 = np.array([11.0, 12.0])
print(ex2.dtype)

float64


In [37]:
# Asignación explícita del tipo de datos
ex3 = np.array([11, 21], dtype=np.int64)
print(ex3.dtype)

int64


In [38]:
# Asignación explícita del tipo de datos convirtiendo los reales a enteros
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [39]:
# Asignación explícita del tipo de datos convirtiendo los enteros a reales
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[ 11.  21.]


# Operaciones Aritméticas con Arrays

In [40]:
# Creamos 2 Arrays
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[ 211.1  212.1]
 [ 221.1  222.1]]


In [41]:
# Suma
print(x + y)
print()
print(np.add(x, y))

[[ 322.1  324.1]
 [ 342.1  344.1]]

[[ 322.1  324.1]
 [ 342.1  344.1]]


In [42]:
# Resta
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [43]:
# Multiplicación
print(x * y)
print()
print(np.multiply(x, y))

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]


In [44]:
# División
print(x / y)
print()
print(np.divide(x, y))

[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]

[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]


In [46]:
# Raiz Cuadrada
print(np.sqrt(x))

[[ 10.53565375  10.58300524]
 [ 11.          11.04536102]]


In [47]:
# Exponencial (e ** x)
print(np.exp(x))

[[  1.60948707e+48   4.37503945e+48]
 [  3.54513118e+52   9.63666567e+52]]


# Operaciones Estadísticas con Arrays

In [48]:
# Crear una matriz aleatoría de 2 x 4
arr = 10 * np.random.randn(2,5)
print(arr)

[[-26.91345418 -20.05327134   6.85265561  12.30201717   4.25938854]
 [  1.52827909  -3.23295146  -0.93979349  10.7241217   -5.10931372]]


In [49]:
# Calcular la Media
print(arr.mean())

-2.05823220768


In [50]:
# Calcular la Media por Filas
print(arr.mean(axis = 1))

[-4.71053284  0.59406842]


In [51]:
# Calcular la Media por Columnas
print(arr.mean(axis = 0))

[-12.69258754 -11.6431114    2.95643106  11.51306943  -0.42496259]


In [52]:
# Calcular la Suma
print(arr.sum())

-20.5823220768


In [53]:
# Calcular la Mediana
print(np.median(arr, axis = 1))

[ 4.25938854 -0.93979349]


# Ordenación de Arrays

In [54]:
# Crear un Array de 10 elementos
unsorted = np.random.randn(10)

print(unsorted)

[ 0.66053964  1.09255268  0.71267803 -0.8492634  -0.07174919  0.67972683
  0.17750327 -0.54871265  0.30519376 -0.57917008]


In [55]:
# Crear una Copia y Ordenar
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-0.8492634  -0.57917008 -0.54871265 -0.07174919  0.17750327  0.30519376
  0.66053964  0.67972683  0.71267803  1.09255268]

[ 0.66053964  1.09255268  0.71267803 -0.8492634  -0.07174919  0.67972683
  0.17750327 -0.54871265  0.30519376 -0.57917008]


In [56]:
# Ordenar
unsorted.sort() 

print(unsorted)

[-0.8492634  -0.57917008 -0.54871265 -0.07174919  0.17750327  0.30519376
  0.66053964  0.67972683  0.71267803  1.09255268]


# Búsqueda de valores únicos en un Array

In [57]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


# Operaciones de conjuntos con un Array

In [58]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [59]:
print( np.intersect1d(s1, s2) ) 

['bulb' 'chair']


In [60]:
print( np.union1d(s1, s2) )

['bulb' 'chair' 'desk' 'lamp']


In [61]:
# Elementos del conjunto s1 que no están en el conjunto s2
print( np.setdiff1d(s1, s2) )

['desk']


In [ ]:
# ¿Qué elementos de s1 están en s2?
print( np.in1d(s1, s2) )

# *Broadcasting*: expansión o adaptación de matrices

Manual de Referencia: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html

In [62]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [64]:
# Crear una Fila con 3 valores
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [65]:
# Sumar Filas
y = start + add_rows
print(y)

[[ 1.  0.  2.]
 [ 1.  0.  2.]
 [ 1.  0.  2.]
 [ 1.  0.  2.]]


In [66]:
# Crear una Columna con 4 valores
add_cols = np.array([[0,1,2,3]])
# Calcular la matriz traspuesta
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [67]:
# Sumar Columnas
y = start + add_cols 
print(y)

[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]


In [68]:
# Sumar un escalar
add_scalar = np.array([1])  
print(start+add_scalar)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


# Test de Velocidad: ndarrays vs lists

In [69]:
# Import Modules
from numpy import arange

# Definir Parámetros
size    = 1000000

In [70]:
# Crear un array con valores 0,1,2,...,size-1
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


In [71]:
# Sumar los elementos de un Array
%timeit nd_array.sum()

528 µs ± 3.06 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [72]:
# Crear una lista con valores 0,1,2,...,size-1
a_list = list(range(size))
print (type(a_list) )

<class 'list'>


In [73]:
# Sumar los elementos de una Lista
%timeit sum(a_list)

33.4 ms ± 308 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Lectura/Escritura de datos en Ficheros

## Formato Binario

In [74]:
x = np.array([ 23.23, 24.24] )

In [75]:
np.save('an_array', x)

In [76]:
np.load('an_array.npy')

array([ 23.23,  24.24])

## Formato Texto

In [77]:
np.savetxt('array.txt', X=x, delimiter=',')

In [79]:
!more array.txt

2.323000000000000043e+01
2.423999999999999844e+01


In [80]:
np.loadtxt('array.txt', delimiter=',')

array([ 23.23,  24.24])

# Otras Operaciones con Arrays

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Dot Product on Matrices and Inner Product on Vectors:

</p>

In [ ]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

In [ ]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

In [ ]:
# dot produce on an array and vector
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sum:
</p>

In [ ]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # add all members

In [ ]:
print(np.sum(ex1, axis=0))  # columnwise sum

In [ ]:
print(np.sum(ex1, axis=1))  # rowwise sum

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Element-wise Functions: </p>

For example, let's compare two arrays values to get the maximum of each.

In [ ]:
# random array
x = np.random.randn(8)
x

In [ ]:
# another random array
y = np.random.randn(8)
y

In [ ]:
# returns element wise maximum between two arrays

np.maximum(x, y)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Reshaping array:
</p>

In [ ]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

In [ ]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Transpose:

</p>

In [ ]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Indexing using where():</p>

In [ ]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [ ]:
out = np.where(filter, x_1, y_1)
print(out)

In [ ]:
mat = np.random.rand(5,5)
mat

In [ ]:
np.where( mat > 0.5, 1000, -1)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

"any" or "all" conditionals:</p>

In [ ]:
arr_bools = np.array([ True, False, True, True, False ])

In [ ]:
arr_bools.any()

In [ ]:
arr_bools.all()

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Random Number Generation:
</p>

In [ ]:
Y = np.random.normal(size = (1,5))[0]
print(Y)

In [ ]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

In [ ]:
np.random.permutation(Z) #return a new ordering of elements in Z

In [ ]:
np.random.uniform(size=4) #uniform distribution

In [ ]:
np.random.normal(size=4) #normal distribution

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Merging data sets:
</p>

In [ ]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

In [ ]:
np.vstack((K,M))

In [ ]:
np.hstack((K,M))

In [ ]:
np.concatenate([K, M], axis = 0)

In [ ]:
np.concatenate([K, M.T], axis = 1)